export const fortunes: string[] = [
  "A surprise is hiding in your left pocket. Check your right pocket instead.",
  "Greatness awaits you. So does your laundry.",
  "You will find what you are looking for... after you stop looking.",
  "The fortune you seek is in another cookie.",
  "Today is a good day to do nothing. Tomorrow, maybe something.",
  "Wealth is just poverty with better snacks.",
  "Someone is thinking about you right now. It might be your dentist.",
  "A wise person knows when to speak. A wiser person knows when to order more dumplings.",
  "Your future is bright. Sunglasses recommended.",
  "The best time to plant a tree was 20 years ago. The second best time is to eat this cookie.",
  "You will live a long life full of healthy choices. Starting after dessert.",
  "Adventure awaits around every corner. Also: a wall.",
  "Patience is a virtue. So is finishing your soup.",
  "The answer you seek is yes. The question was probably about noodles.",
  "You are smarter than you think. Your phone is smarter than both of you.",
  "Opportunity knocks once. Delivery drivers knock twice.",
  "Be yourself. Everyone else is already taken and slightly exhausted.",
  "A goal without a plan is just a wish. A plan without snacks is just suffering.",
  "You will soon make a decision that changes everything. Pick the soup dumpling.",
  "The stars align in your favor. The planets are still debating.",
  "Hard work pays off. So does being extremely lucky.",
  "A journey of a thousand miles begins with a single step and very good shoes.",
  "Your kindness will return to you threefold. Or in the form of a free egg roll.",
  "Success is not final. Neither is that last piece of General Tso's chicken.",
  "You have the power to change the world. Start with your inbox.",
  "Love is around the corner. So is a very good parking spot.",
  "The secret ingredient is always butter. Or friendship. Mostly butter.",
  "Do not worry about tomorrow. Tomorrow's menu has already been decided.",
  "A pleasant surprise is coming your way. It is not this fortune.",
  "You will soon receive good news. Unless this IS the news.",
  "Happiness is not a destination. It is a very comfortable chair.",
  "Your talents are recognized. Mostly by you, but that counts.",
  "A small act of courage today leads to a big story tomorrow.",
  "The tea is always hotter than it looks. So are your ideas.",
  "You are exactly where you need to be. Unless you are lost, in which case: left.",
  "Every ending is a new beginning. Every new beginning comes with a coupon.",
  "Trust your instincts. They have been to this restaurant before.",
  "The wisest person in the room is usually the quietest. Or asleep.",
  "You will find harmony between work and rest. Probably this weekend.",
  "Something you lost will be found. Check under the couch cushions.",
  "A chance encounter will lead to an unexpected friendship. Possibly with a cat.",
  "Your energy is contagious. Please wash your hands.",
  "The universe has a plan for you. It involves more vegetables.",
  "Laughter is the best medicine. This fortune is not a substitute for real medicine.",
  "You are capable of more than you know. Especially after coffee.",
  "A new chapter in your life begins soon. You wrote the last one.",
  "The simplest solution is usually the right one. Also the most boring.",
  "What you focus on grows. Choose wisely. Or choose noodles.",
  "Your creativity will solve a problem today. Probably not the big one.",
  "Fortune favors the bold. And those who arrive early to brunch.",
  "You will soon cross a bridge. Look both ways. Also: metaphor.",
  "Inner peace is just one deep breath away. And several weeks of therapy.",
  "The moon is in your corner tonight. Do not ask what this means.",
  "You attract what you put out. Currently: a faint smell of takeout.",
  "Today's struggle is tomorrow's strength. Tonight is just tonight.",
  "A compliment is coming your way. You do look nice, by the way.",
  "The best view comes after the hardest climb. Or just buy a window seat.",
  "Your path is unique. So are your passwords, hopefully.",
  "Do more of what makes you happy. Do less of what makes you weird.",
  "You will soon master a new skill. Chopsticks count.",
  "Somewhere, someone is proud of you. Possibly this cookie.",
  "Beware of free advice. Except this fortune, which was not free.",
  "Your best days are still ahead. Your best naps may also be ahead.",
  "Change is the only constant. Also: rent.",
  "You have more friends than you realize. Some of them are just very quiet.",
  "The obstacle in your path is not as big as it looks. It is exactly that big. Good luck.",
  "A small risk taken today will grow into a large reward tomorrow.",
  "Magic is real. It is called a very good recipe.",
  "You are on the right track. The train is running late but it is coming.",
  "Curiosity did not kill the cat. The cat is fine. Be curious.",
  "Your greatest strengths are patience and not showing your hand. Also: you're easy to read.",
  "Life is short. Order the good tea.",
  "Everything you need is already within you. And also at the grocery store.",
  "A new opportunity will arrive before you finish chewing.",
  "The best stories start with 'you won't believe what happened.'",
  "You will inspire someone today without even trying.",
  "Embrace the unknown. It has been waiting for you to stop ignoring it.",
  "Today is someone's favorite day ever. Make sure it is yours.",
  "What seems impossible now will seem obvious later. After more sleep.",
  "Your next big idea is one shower thought away.",
  "Balance is key. Also: a good sauce-to-noodle ratio.",
  "Let go of what no longer serves you. Especially that one group chat.",
  "A door is closing. A window is opening. Also: check your HVAC.",
  "The right moment is never perfect. It just has better lighting.",
  "You will leave a lasting impression wherever you go.",
  "Sometimes the best plan is no plan. This is rarely true but occasionally correct.",
  "Your cup is half full. Also, you should finish that before it gets cold.",
  "Forgiveness is a gift you give yourself. Refunds are a gift you give others.",
  "You are not stuck. You are pausing dramatically before the next act.",
  "A second chance is on its way. Don't waste the first one waiting for it.",
  "The answer is simpler than the question suggests. The question was already pretty simple.",
  "You are braver than you believe. The fortune cookie believes in you.",
  "Not all those who wander are lost. Some are just looking for parking.",
  "The right words will come to you at the right time. Probably 3am.",
  "Your story is still being written. Put down the phone and write it.",
  "Good things take time. Great things take a reservation.",
  "You will find exactly what you need. Not what you want. What you need.",
  "The universe is listening. Speak clearly and tip well.",
  "Today you are exactly enough. Tomorrow: still enough, but with better posture.",
  "A cookie told you this. That should mean something.",
];
